apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: appconfig-ai-service
spec:
  type: configuration.redis
  version: v1
  metadata:
    - name: redisHost
      value: 192.168.1.160:6379
    - name: redisDb
      value: "1"
scopes:
  - ai-service
